Prevent configuring for a user emulator on a different type of OS
Signed-off-by: Blue Swirl <blauwirbel@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2172,14 +2172,26 @@ case "$target" in
     target_softmmu="yes"
     ;;
   ${target_arch2}-linux-user)
+    if test "$linux" != "yes" ; then
+      echo "ERROR: Target '$target' is only available on a Linux host"
+      exit 1
+    fi
     target_user_only="yes"
     target_linux_user="yes"
     ;;
   ${target_arch2}-darwin-user)
+    if test "$darwin" != "yes" ; then
+      echo "ERROR: Target '$target' is only available on a Darwin host"
+      exit 1
+    fi
     target_user_only="yes"
     target_darwin_user="yes"
     ;;
   ${target_arch2}-bsd-user)
+    if test "bsd" != "yes" ; then
+      echo "ERROR: Target '$target' is only available on a BSD host"
+      exit 1
+    fi
     target_user_only="yes"
     target_bsd_user="yes"
     ;;
