------------------------------------------------------------------------ r4924 | aliguori | 2008-07-23 02:58:33 +0200 (Mi, 23 Jul 2008) | 8 lines
Fix -daemonize option

When using -daemonize, we want to avoid chdir() until after we've opened the
block devices.  It's also perfectly fine to use -dameonize along with SDL.

Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>


------------------------------------------------------------------------
r4925 | aliguori | 2008-07-23 15:24:33 +0200 (Mi, 23 Jul 2008) | 10 lines

Fix SDL problems with BGR displays (Avi Kivity)

revert qemu's sdl.c rev 1.40

this fixes problems with bgr displays.

Signed-off-by: Avi Kivity <avi@qumranet.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>


------------------------------------------------------------------------
r4926 | aliguori | 2008-07-23 15:29:23 +0200 (Mi, 23 Jul 2008) | 8 lines

Fix task register type after reset (Avi Kivity)

Obvious typo that breaks reboots.

Signed-off-by: Avi Kivity <avi@qumranet.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>


------------------------------------------------------------------------
r4927 | aliguori | 2008-07-23 17:19:59 +0200 (Mi, 23 Jul 2008) | 9 lines

Save 3MB ioport table memory (Samuel Thibault)

Save 1.5MB (32bit) or 3MB (64bit) memory by keeping ioport tables
sparse and use a test against NULL instead.

Signed-off-by: Samuel Thibault <samuel.thibault@eu.citrix.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>


------------------------------------------------------------------------
r4928 | ths | 2008-07-23 18:14:22 +0200 (Mi, 23 Jul 2008) | 2 lines

Less hardcoding of TARGET_USER_ONLY.

------------------------------------------------------------------------
r4929 | ths | 2008-07-23 18:16:31 +0200 (Mi, 23 Jul 2008) | 2 lines

Use plain standard inline.

------------------------------------------------------------------------
r4930 | balrog | 2008-07-23 18:35:45 +0200 (Mi, 23 Jul 2008) | 2 lines

Add OneNAND Unlock All command (Kyungmin Park).

------------------------------------------------------------------------
r4931 | aliguori | 2008-07-23 20:14:33 +0200 (Mi, 23 Jul 2008) | 8 lines

Enable VDE by default if library is present.

VDE isn't used unless the user explicitly asks for it so if the library is
present on the system, we should include support for it.

Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>


------------------------------------------------------------------------
r4932 | malc | 2008-07-23 21:17:46 +0200 (Mi, 23 Jul 2008) | 9 lines

Preliminary PPC64/Linux host support

ppc64.ld from Heikki Lindholm's patch
http://marc.info/?l=qemu-devel&m=114086179024634&w=2

Issues:
x86_64 tripple faults shortly after decompressing the kernel
No immediate versions of most 64 bit operations
More...
------------------------------------------------------------------------
r4933 | malc | 2008-07-23 22:01:19 +0200 (Mi, 23 Jul 2008) | 1 line

Remove stray "i" from mul_i64
------------------------------------------------------------------------
r4934 | malc | 2008-07-23 22:01:23 +0200 (Mi, 23 Jul 2008) | 1 line

Provide extNs_M instructions
------------------------------------------------------------------------
r4935 | malc | 2008-07-23 22:01:27 +0200 (Mi, 23 Jul 2008) | 1 line

Remove neg_i32 debugging leftover
------------------------------------------------------------------------


git-svn-id: svn+ssh://svn.berlios.de/svnroot/repos/ar7-firmware/qemu/trunk@1181 11fd3d49-aaf6-0310-8052-ea9566248e5e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -89,7 +89,7 @@ mingw32="no"
 EXESUF=""
 gdbstub="yes"
 slirp="yes"
-vde="no"
+vde="yes"
 fmod_lib=""
 fmod_inc=""
 vnc_tls="yes"
@@ -281,7 +281,7 @@ for opt do
   ;;
   --disable-slirp) slirp="no"
   ;;
-  --enable-vde) vde="yes"
+  --disable-vde) vde="no"
   ;;
   --disable-kqemu) kqemu="no"
   ;;
@@ -436,7 +436,7 @@ echo "  --fmod-lib               path to FMOD library"
 echo "  --fmod-inc               path to FMOD includes"
 echo "  --enable-uname-release=R Return R for uname -r in usermode emulation"
 echo "  --sparc_cpu=V            Build qemu for Sparc architecture v7, v8, v8plus, v8plusa, v9"
-echo "  --enable-vde             enable support for vde network [$vde]"
+echo "  --disable-vde            disable support for vde network"
 echo ""
 echo "NOTE: The object files are built at the place where configure is launched"
 exit 1
@@ -642,6 +642,24 @@ if test "$cpu" = "x86_64" \
     hostlongbits="64"
 fi
 
+# ppc specific hostlongbits selection
+if test "$cpu" = "powerpc" ; then
+    cat > $TMPC <<EOF
+int main(void){return sizeof(long);}
+EOF
+
+    if $cc $ARCH_CFLAGS -o $TMPE $TMPC 2> /dev/null; then
+        $TMPE
+        case $? in
+            4) hostlongbits="32";;
+            8) hostlongbits="64";;
+            *) echo "Couldn't determine bits per long value";;
+        esac
+    else
+        echo hostlongbits test failed
+    fi
+fi
+
 # check gcc options support
 cat > $TMPC <<EOF
 int main(void) {
@@ -740,11 +758,7 @@ EOF
     if $cc $ARCH_CFLAGS -o $TMPE $TMPC 2> /dev/null ; then
         :
     else
-        echo
-        echo "Error: VDE check failed"
-        echo "Make sure to have the VDE libs and headers installed."
-        echo
-        exit 1
+        vde="no"
     fi
 fi
 
@@ -1004,8 +1018,13 @@ case "$cpu" in
     echo "#define HOST_MIPS64 1" >> $config_h
   ;;
   powerpc)
-    echo "ARCH=ppc" >> $config_mak
-    echo "#define HOST_PPC 1" >> $config_h
+  if test "$hostlongbits" = "32"; then
+      echo "ARCH=ppc" >> $config_mak
+      echo "#define HOST_PPC 1" >> $config_h
+  else
+      echo "ARCH=ppc64" >> $config_mak
+      echo "#define HOST_PPC64 1" >> $config_h
+  fi
   ;;
   s390)
     echo "ARCH=s390" >> $config_mak
