Configure check for graphical output (Paul Brook)
git-svn-id: svn://svn.savannah.nongnu.org/qemu/trunk@1460 c046a42c-6fe2-441c-8c8c-71466251a162

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -84,6 +84,7 @@ linux="no"
 kqemu="no"
 kernel_path=""
 cocoa="no"
+check_gfx="yes"
 
 # OS specific
 targetos=`uname -s`
@@ -186,6 +187,8 @@ for opt do
   ;; 
   --enable-cocoa) cocoa="yes" ; sdl="no"
   ;; 
+  --disable-gfx-check) check_gfx="no"
+  ;;
   esac
 done
 
@@ -611,6 +614,14 @@ fi
 target_user_only="no"
 if expr $target : '.*-user' > /dev/null ; then
   target_user_only="yes"
+fi
+
+if test "$target_user_only" = "no" -a "$check_gfx" = "yes" \
+	-a "$sdl" = "no" -a "$cocoa" = "no" ; then
+    echo "ERROR: QEMU requires SDL or Cocoa for graphical output"
+    echo "To build QEMU with graphical output configure with --disable-gfx-check"
+    echo "Note that this will disable all output from the virtual graphics card."
+    exit 1;
 fi
 
 #echo "Creating $config_mak, $config_h and $target_dir/Makefile"
