------------------------------------------------------------------------ r4936 | blueswir1 | 2008-07-24 13:25:30 +0200 (Do, 24 Jul 2008) | 1 line
Fix detection of 15 bit display depth
------------------------------------------------------------------------
r4937 | blueswir1 | 2008-07-24 13:26:38 +0200 (Do, 24 Jul 2008) | 1 line

Fix 24 bit mode
------------------------------------------------------------------------
r4938 | blueswir1 | 2008-07-24 13:28:51 +0200 (Do, 24 Jul 2008) | 1 line

Sparc32: save/load all MMU registers, Sparc64: add CPU save/load
------------------------------------------------------------------------
r4939 | malc | 2008-07-24 19:37:09 +0200 (Do, 24 Jul 2008) | 4 lines

Emit and use adhoc function descriptor for code_gen_prologue on PPC64

Thus avoiding fragile inline assembly hackery to call into generated
code.
------------------------------------------------------------------------
r4940 | malc | 2008-07-24 19:51:36 +0200 (Do, 24 Jul 2008) | 1 line

Do exit if test for hostlongbits on ppc64 fails
------------------------------------------------------------------------
r4941 | malc | 2008-07-25 00:56:21 +0200 (Fr, 25 Jul 2008) | 1 line

Use proper value for TCG_TARGET_CALL_STACK_OFFSET
------------------------------------------------------------------------
r4942 | blueswir1 | 2008-07-25 09:42:14 +0200 (Fr, 25 Jul 2008) | 1 line

Make MAXTL dynamic, bounds check tl when indexing
------------------------------------------------------------------------
r4943 | balrog | 2008-07-25 23:07:21 +0200 (Fr, 25 Jul 2008) | 2 lines

Fix OMAP GPMC register offsets and SYSCTL 8bit io (Kyungmin Park).

------------------------------------------------------------------------
r4944 | edgar_igl | 2008-07-25 23:20:21 +0200 (Fr, 25 Jul 2008) | 1 line

CRIS: Correct condition for when to apply fast move flags evaluation. Correct single-stepping over branches.
------------------------------------------------------------------------
r4945 | malc | 2008-07-26 13:20:44 +0200 (Sa, 26 Jul 2008) | 1 line

Fix EXTSW arguments
------------------------------------------------------------------------
r4946 | malc | 2008-07-26 13:20:50 +0200 (Sa, 26 Jul 2008) | 1 line

Fix and improve 64 bit immediate loading
------------------------------------------------------------------------
r4947 | malc | 2008-07-26 13:20:54 +0200 (Sa, 26 Jul 2008) | 1 line

Reduce amount of space reserved for tb jump
------------------------------------------------------------------------
r4948 | malc | 2008-07-26 13:20:57 +0200 (Sa, 26 Jul 2008) | 1 line

Use proper offset for LR save slot
------------------------------------------------------------------------
r4949 | malc | 2008-07-26 13:21:00 +0200 (Sa, 26 Jul 2008) | 1 line

Fix qemu_ld64 constraint list
------------------------------------------------------------------------
r4950 | malc | 2008-07-26 13:21:03 +0200 (Sa, 26 Jul 2008) | 1 line

Relax memory operations constraints
------------------------------------------------------------------------
r4951 | blueswir1 | 2008-07-26 17:05:57 +0200 (Sa, 26 Jul 2008) | 1 line

Map code buffers below 2G on Sparc64
------------------------------------------------------------------------
r4952 | aliguori | 2008-07-26 18:53:22 +0200 (Sa, 26 Jul 2008) | 5 lines

Add e1000 etherboot ROM from http://www.rom-o-matic.net

Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>


------------------------------------------------------------------------
r4953 | blueswir1 | 2008-07-26 19:19:35 +0200 (Sa, 26 Jul 2008) | 1 line

Try to avoid glibc global register mangling, again
------------------------------------------------------------------------


git-svn-id: svn+ssh://svn.berlios.de/svnroot/repos/ar7-firmware/qemu/trunk@1182 11fd3d49-aaf6-0310-8052-ea9566248e5e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -653,10 +653,11 @@ EOF
         case $? in
             4) hostlongbits="32";;
             8) hostlongbits="64";;
-            *) echo "Couldn't determine bits per long value";;
+            *) echo "Couldn't determine bits per long value"; exit 1;;
         esac
     else
         echo hostlongbits test failed
+        exit 1
     fi
 fi
 
