configure: Allow compilation without glib-2.0
glib-2.0 is not needed for mingw and basic cross compilations.

Signed-off-by: Stefan Weil <weil@mail.berlios.de>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1882,8 +1882,8 @@ if $pkg_config --modversion glib-2.0 > /dev/null 2>&1 ; then
 elif test "$mingw32" = "yes" ; then
     echo "mingw32 without glib-2.0"
 else
-    echo "glib-2.0 required to compile QEMU"
-    exit 1
+    echo "glib-2.0 required to compile QEMU, trying without it"
+    #~ exit 1
 fi
 
 ##########################################
